name: cmdb-kubeexplorer-desktop
arch: amd64
platform: linux
version: ${VERSION}
maintainer: CMDB <support@cmdb.io>
description: "Kubernetes visibility â€” topology, traffic, and Helm management"
vendor: CMDB
homepage: https://github.com/cmdb/kubeexplorer
license: Apache-2.0
contents:
  - src: build/bin/cmdb-kubeexplorer-desktop
    dst: /usr/bin/cmdb-kubeexplorer-desktop
  - src: deploy/linux/cmdb-kubeexplorer-desktop.desktop
    dst: /usr/share/applications/cmdb-kubeexplorer-desktop.desktop
  - src: build/appicon.png
    dst: /usr/share/icons/hicolor/32x32/apps/cmdb-kubeexplorer-desktop.png
overrides:
  deb:
    depends:
      - libgtk-3-0
      - libwebkit2gtk-4.0-37
  rpm:
    depends:
      - gtk3
      - webkit2gtk4.0
